USE HW11DB;

CREATE TABLE Departments (
id INT(20) PRIMARY KEY,
name VARCHAR(30) NOT NULL
);

CREATE TABLE Roles (
id INT(10) PRIMARY KEY,
title VARCHAR(30) NOT NULL,
salary DECIMAL(10,2) NOT NULL,
department_id INT NOT NULL
);

CREATE TABLE Employees (
ID INT(10) PRIMARY KEY,
first_name VARCHAR(30) NOT NULL,
last_night VARCHAR(30) NOT NULL,
role_id INT NOT NULL,
manager_id INT NOT NULL
);

