CREATE DATABASE HW11DB;

USE HW11DB;

CREATE TABLE Departments (
id INTEGER AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(30) NOT NULL
);

CREATE TABLE Roles (
id INTEGER AUTO_INCREMENT PRIMARY KEY,
title VARCHAR(30) NOT NULL,
salary DECIMAL(10,2) NOT NULL,
department_id INT NOT NULL
);

CREATE TABLE Employees (
ID INTEGER AUTO_INCREMENT PRIMARY KEY,
first_name VARCHAR(30) NOT NULL,
last_night VARCHAR(30) NOT NULL,
role_id INT NOT NULL,
manager_id INT NOT NULL
);

